In [3]:
#1 additioin of two user defined number
x = input()
y = input()

print(int(x) + int(y))


85
85
170


In [4]:
#2 to check whether a number is Armstrong or not

def is_armstrong(n):
    a = str(n)
    b = len(a)
    total = 0
    for digit in a:
        total += int(digit) ** b
    return total == n

# Test the function
a = int(input("Enter a number: "))
if is_armstrong(a):
    print(a, "is an Armstrong number")
else:
    print(a, "is not an Armstrong number")

Enter a number: 153
153 is an Armstrong number


In [1]:
#3 to check whether a number is prime or not

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Test the function
n = int(input("Enter a number: "))
if is_prime(n):
    print(n, "is a prime number")
else:
    print(n, "is not a prime number")


Enter a number: 85
85 is not a prime number


In [5]:
#4 to check largest element of an aaray User Defined
def longest_element(arr):
    max_length = 0
    longest = ""
    for element in arr:
        if len(element) > max_length:
            max_length = len(element)
            longest = element
    return longest

# Test the function
arr = input("Enter elements of the array separated by spaces: ").split()
longest = longest_element(arr)
print("Longest element in the array is:", longest)

Enter elements of the array separated by spaces: apple banana kiwi watermelon
Longest element in the array is: watermelon


In [ ]:
#5 Swap 2 elements of a list in python (user defined position)
# User input for list elements
user_list = input("Enter elements of the list separated by space: ").split()

# Display the original list
print("Original list:", user_list)

# User input for positions of elements to swap
pos1 = int(input("Enter position of the first element to swap (starting from 0): "))
pos2 = int(input("Enter position of the second element to swap (starting from 0): "))

# Swap the elements at the given positions
user_list[pos1], user_list[pos2] = user_list[pos2], user_list[pos1]

# Display the list after swapping
print("List after swapping:", user_list)


Enter elements of the list separated by space: potato orange apple
Original list: ['potato', 'orange', 'apple']
Enter position of the first element to swap (starting from 0): 1
Enter position of the second element to swap (starting from 0): 2
List after swapping: ['potato', 'apple', 'orange']


In [1]:
#6 reversing a list
# Input numbers from the user separated by space and convert them into a list of integers
my_list = [int(x) for x in input("Enter the numbers separated by spaces: ").split()]

print("The original list:", my_list)

# Reverse the list using the reverse() method
reversed_list = my_list[::-1]

print("The reversed list:", reversed_list)

Enter the numbers separated by spaces: 85 36 25 96 78 1315
The original list: [85, 36, 25, 96, 78, 1315]
The reversed list: [1315, 78, 96, 25, 36, 85]


In [2]:
#7 Finding odd and even number in a list
list1 =[int (x) for x in input("Enter elements of the list seperated by space:").split()]

odd = []
even = []

for number in list1:
    if number % 2 == 0:
        even.append(number)
    else:
        odd.append(number)

print ("Odd numbers:", odd)
print ("Even numbers:", even)

Enter elements of the list seperated by space:44 66 63 52 58 59 74 79 77 
Odd numbers: [63, 59, 79, 77]
Even numbers: [44, 66, 52, 58, 74]


In [ ]:
#8 addition of 2 matrix
import numpy as np
x = [[1,2,3], [4,5,6], [7,8,9]]
y = [[9,8,7,], [6,5,4,], [3,2,1]]
r = np.array(x)+np.array(y)
print(r)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#9 Multiplication of two matrix
import numpy as np
x = [[1,2], [3,4]]
y = [[5,6], [7,8]]
r = np.dot(x,y)
print(r)


[[19 22]
 [43 50]]


In [1]:
#10 checking a palindrome number
def is_palindrome(n):
    return str(n) == str(n)[::-1]
n = int(input("Enter a number:"))

if is_palindrome(n):
    print(n, "is a palindrome number")
else:
    print(n, "is not a palindrome number")

Enter a number:789987
789987 is a palindrome number


In [41]:
#11 fniding the size of a tuple
my_tuple = (1, 2, 3, 'a', 'b', 'c')

tuple_size = len(my_tuple)

print(tuple_size)

6


In [2]:
#12 Printing current date and time
from pytz import timezone 
from datetime import datetime

ind_time = datetime.now(timezone("Asia/Kolkata"))
print(ind_time)

Current Indian date and time: 2024-02-26 11:56:53.269362+05:30


In [8]:
#13 Python code for printing pattern G
pattern = ""
pattern += " ****\n"
pattern += "*    \n"
pattern += "*  ***\n"
pattern += "*   *\n"
pattern += " *** \n"

print(pattern)


 ****
*    
*  ***
*   *
 *** 



In [3]:
#14 Pyhton code for sum of an array
array = [int(x) for x in input("Enter the array elements seperated by spaces").split()]
print("the sum of the array is:", sum(array))

Enter the array elements seperated by spaces852 369 741 52 56 36
the sum of the array is: 2106


In [4]:
#15 To find sum of squares of first n user defined natural number

# Get user input for the value of 'n'
n = int(input("Enter the value of 'n': "))

# Calculate the sum of squares of first n natural numbers
sum_of_squares = sum([i**2 for i in range(1, n+1)])

# Print the result
print("Sum of squares of the first", n, "natural numbers:", sum_of_squares)


Enter the value of 'n': 9
Sum of squares of the first 9 natural numbers: 285


In [11]:
#16 To find and print all vowels present in a string
# Function to find and print all vowels in a string
def print_vowels(string):
    vowels = "aeiouAEIOU"  # Define a string containing all vowels
    # Iterate through each character in the string
    for char in string:
        # Check if the character is a vowel
        if char in vowels:
            print(char, end=" ")  # Print the vowel

# Input string from the user
string = input("Enter a string: ")

# Call the function to print vowels in the string
print("Vowels in the string:", end=" ")
print_vowels(string)


Enter a string: Sukanya
Vowels in the string: u a a 

In [12]:
#17 to calculate Euclidean distance between two points (user defined)
import math
def euclidean_distance(x1, y1, x2, y2):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

x1 = float(input("Enter the x-coordinate of the first point: "))
y1 = float(input("Enter the y-coordinate of the first point: "))
x2 = float(input("Enter the x-coordinate of the second point: "))
y2 = float(input("Enter the y-coordinate of the second point: "))

distance = euclidean_distance(x1, y1, x2, y2)
print("The Euclidean distance between the two points is:", distance)


Enter the x-coordinate of the first point: 45
Enter the y-coordinate of the first point: 65
Enter the x-coordinate of the second point: 85
Enter the y-coordinate of the second point: 58
The Euclidean distance between the two points is: 40.607881008493905


In [1]:
#18a Function for linear search of a string in a list
def linear_search(string, lst):
    for i in range(len(lst)):
        if lst[i] == string:
            return f"String '{string}' found at index {i}"
    return f"String '{string}' not found in the list"

# Test the function
my_list = input("Enter a list of strings separated by spaces: ").split()
search_string = input("Enter the string to search in the list: ")

result = linear_search(search_string, my_list)
print(result)

Enter a list of strings separated by spaces: Nepal Bhutan Bangladesh India
Enter the string to search in the list: Bhutan
String 'Bhutan' found at index 1


In [16]:
#18b Function for linear search of a number in a list
def linear_search(int, lst):
    for i in range(len(lst)):
        if lst[i] == int:
            return f"Int '{int}' found at index {i}"
    return f"Int '{int}' not found in the list"

# Test the function
my_list = input("Enter a list of numbers separated by spaces: ").split()
search_string = input("Enter the numbers to search in the list: ")

result = linear_search(search_string, my_list)
print(result)

Enter a list of numbers separated by spaces: 789 456 123 321 654 987 785 985 125 325 
Enter the numbers to search in the list: 987
Int '987' found at index 5


In [13]:
#19 To find the smallest number in a list

# Get user input for the list of numbers
numbers = [int(x) for x in input("Enter the list of numbers separated by spaces: ").split()]

# Find the smallest number in the list
smallest_number = min(numbers)

print("The smallest number in the list is:", smallest_number)

Enter the list of numbers separated by spaces: 12 45 85 -85 -96
The smallest number in the list is: -96


In [66]:
 #20 To find the largest number in a list

# Get user input for the list of numbers
numbers = [int(x) for x in input("Enter the list of numbers separated by spaces: ").split()]

# Find the largest number in the list
largest_number = max(numbers)

print("The largest number in the list is:", largest_number)


Enter the list of numbers separated by spaces: 85 25 63
The largest number in the list is: 85
